
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<Config> {
    return await TAURI_INVOKE("get_config");
},
async saveConfig(config: Config) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Single entry point for all app updates. The frontend calls this once per app.
 * 
 * Each invocation reads config from disk independently — this is inherent to the
 * Tauri IPC model where each `invoke` call is a separate request. At the current
 * scale (~5 apps, tiny JSON file) this is fine.
 */
async updateApp(app: AppName, theme: ThemeContext) : Promise<UpdateResult> {
    return await TAURI_INVOKE("update_app", { app, theme });
},
/**
 * Toggle system-wide dark/light mode. Separate from update_app because system
 * appearance is not an app with AppConfig — it's a standalone boolean toggle.
 */
async updateSystemAppearance(appearance: string) : Promise<UpdateResult> {
    return await TAURI_INVOKE("update_system_appearance", { appearance });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppConfig = { enabled?: boolean; config_path: string; themes_path?: string | null; match_pattern?: string | null; replace_template?: string | null }
/**
 * Supported app names. TypeScript bindings are auto-generated via tauri-specta.
 */
export type AppName = "nvim" | "tmux" | "ghostty" | "zed" | "delta" | "lazygit" | "obsidian"
export type Config = { system_appearance: boolean; apps: { [key in AppName]: AppConfig } }
/**
 * Theme metadata passed from the frontend.
 */
export type ThemeContext = { theme_key: string; appearance: string; collection_key: string; theme_label: string | null }
export type UpdateResult = { app: string; status: UpdateStatus; message?: string | null }
export type UpdateStatus = "done" | "error" | "skipped"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
