/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as DevRouteRouteImport } from './routes/dev/route.tsx'
import { Route as AppRouteRouteImport } from './routes/_app/route.tsx'
import { Route as DevIndexRouteImport } from './routes/dev/index.tsx'
import { Route as AppIndexRouteImport } from './routes/_app/index.tsx'
import { Route as DevTypographyRouteImport } from './routes/dev/typography.tsx'
import { Route as DevPrimitivesRouteImport } from './routes/dev/primitives.tsx'
import { Route as DevComponentsRouteImport } from './routes/dev/components.tsx'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route.tsx'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index.tsx'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general.tsx'
import { Route as AppSettingsAdaptersIndexRouteImport } from './routes/_app/settings/adapters/index.tsx'
import { Route as AppSettingsAdaptersAdapterRouteImport } from './routes/_app/settings/adapters/$adapter.tsx'

const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DevTypographyRoute = DevTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevPrimitivesRoute = DevPrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DevRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAdaptersIndexRoute =
  AppSettingsAdaptersIndexRouteImport.update({
    id: '/adapters/',
    path: '/adapters/',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsAdaptersAdapterRoute =
  AppSettingsAdaptersAdapterRouteImport.update({
    id: '/adapters/$adapter',
    path: '/adapters/$adapter',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/dev/components': typeof DevComponentsRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/typography': typeof DevTypographyRoute
  '/dev/': typeof DevIndexRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/settings/adapters/$adapter': typeof AppSettingsAdaptersAdapterRoute
  '/settings/adapters/': typeof AppSettingsAdaptersIndexRoute
}
export interface FileRoutesByTo {
  '/dev/components': typeof DevComponentsRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/typography': typeof DevTypographyRoute
  '/': typeof AppIndexRoute
  '/dev': typeof DevIndexRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/adapters/$adapter': typeof AppSettingsAdaptersAdapterRoute
  '/settings/adapters': typeof AppSettingsAdaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/dev/components': typeof DevComponentsRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/typography': typeof DevTypographyRoute
  '/_app/': typeof AppIndexRoute
  '/dev/': typeof DevIndexRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/settings/adapters/$adapter': typeof AppSettingsAdaptersAdapterRoute
  '/_app/settings/adapters/': typeof AppSettingsAdaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/settings'
    | '/dev/components'
    | '/dev/primitives'
    | '/dev/typography'
    | '/dev/'
    | '/settings/general'
    | '/settings/'
    | '/settings/adapters/$adapter'
    | '/settings/adapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev/components'
    | '/dev/primitives'
    | '/dev/typography'
    | '/'
    | '/dev'
    | '/settings/general'
    | '/settings'
    | '/settings/adapters/$adapter'
    | '/settings/adapters'
  id:
    | '__root__'
    | '/_app'
    | '/dev'
    | '/_app/settings'
    | '/dev/components'
    | '/dev/primitives'
    | '/dev/typography'
    | '/_app/'
    | '/dev/'
    | '/_app/settings/general'
    | '/_app/settings/'
    | '/_app/settings/adapters/$adapter'
    | '/_app/settings/adapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DevRouteRoute: typeof DevRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dev/typography': {
      id: '/dev/typography'
      path: '/typography'
      fullPath: '/dev/typography'
      preLoaderRoute: typeof DevTypographyRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/primitives': {
      id: '/dev/primitives'
      path: '/primitives'
      fullPath: '/dev/primitives'
      preLoaderRoute: typeof DevPrimitivesRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/adapters/': {
      id: '/_app/settings/adapters/'
      path: '/adapters'
      fullPath: '/settings/adapters/'
      preLoaderRoute: typeof AppSettingsAdaptersIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/adapters/$adapter': {
      id: '/_app/settings/adapters/$adapter'
      path: '/adapters/$adapter'
      fullPath: '/settings/adapters/$adapter'
      preLoaderRoute: typeof AppSettingsAdaptersAdapterRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsAdaptersAdapterRoute: typeof AppSettingsAdaptersAdapterRoute
  AppSettingsAdaptersIndexRoute: typeof AppSettingsAdaptersIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsAdaptersAdapterRoute: AppSettingsAdaptersAdapterRoute,
  AppSettingsAdaptersIndexRoute: AppSettingsAdaptersIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DevRouteRouteChildren {
  DevComponentsRoute: typeof DevComponentsRoute
  DevPrimitivesRoute: typeof DevPrimitivesRoute
  DevTypographyRoute: typeof DevTypographyRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevComponentsRoute: DevComponentsRoute,
  DevPrimitivesRoute: DevPrimitivesRoute,
  DevTypographyRoute: DevTypographyRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  DevRouteRoute: DevRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
