/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as SettingsRouteRouteImport } from './routes/settings/route.tsx'
import { Route as DevRouteRouteImport } from './routes/dev/route.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as DevIndexRouteImport } from './routes/dev/index.tsx'
import { Route as DevTypographyRouteImport } from './routes/dev/typography.tsx'
import { Route as DevPrimitivesRouteImport } from './routes/dev/primitives.tsx'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevTypographyRoute = DevTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevPrimitivesRoute = DevPrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => DevRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/typography': typeof DevTypographyRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/typography': typeof DevTypographyRoute
  '/dev': typeof DevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/typography': typeof DevTypographyRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/settings'
    | '/dev/primitives'
    | '/dev/typography'
    | '/dev/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/dev/primitives' | '/dev/typography' | '/dev'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/settings'
    | '/dev/primitives'
    | '/dev/typography'
    | '/dev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRouteRoute: typeof DevRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/typography': {
      id: '/dev/typography'
      path: '/typography'
      fullPath: '/dev/typography'
      preLoaderRoute: typeof DevTypographyRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/primitives': {
      id: '/dev/primitives'
      path: '/primitives'
      fullPath: '/dev/primitives'
      preLoaderRoute: typeof DevPrimitivesRouteImport
      parentRoute: typeof DevRouteRoute
    }
  }
}

interface DevRouteRouteChildren {
  DevPrimitivesRoute: typeof DevPrimitivesRoute
  DevTypographyRoute: typeof DevTypographyRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevPrimitivesRoute: DevPrimitivesRoute,
  DevTypographyRoute: DevTypographyRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRouteRoute: DevRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
